/********************************************************************
 This file was generated by menu Tool of Rockchip Co., Ltd.

 Generate time: 2013-3-27 16:29:1

 Tool Version: 3.0.0.0

 End.
********************************************************************/
#ifndef          _MENU_RESOURCE_H
#define          _MENU_RESOURCE_H


#define          PID_MUSIC                    (unsigned short)0x0000
#define          PID_SET                      (unsigned short)0x0001

#define          MENU_ITEM_LENGTH            (unsigned short)258             // The length of menu item in bytes
#define          TOTAL_MENU_ITEM             (unsigned short)197
#define          TOTAL_LANAUAGE_NUM          (unsigned short)21
#define          MAX_SUBMENU_NUM             (unsigned short)21
#define          MENU_CONTENT_OFFSET         (unsigned short)58





#define          SID_MUSIC                                        (unsigned short)0x0000       //Music
#define          SID_RADIO                                        (unsigned short)0x0001       //Radio
#define          SID_RECORD                                       (unsigned short)0x0002       //Record
#define          SID_TEXT                                         (unsigned short)0x0003       //Text
#define          SID_EXPLORER                                     (unsigned short)0x0004       //Explorer
#define          SID_MAIN_SETTINGS                                (unsigned short)0x0005       //Settings
#define          SID_VIDEO                                        (unsigned short)0x0006       //Video
#define          SID_PHOTO                                        (unsigned short)0x0007       //Photo
#define          SID_FM_RADIO                                     (unsigned short)0x0008       //FM Radio
#define          SID_NOR                                          (unsigned short)0x0009       //NOR
#define          SID_PLAYFX                                       (unsigned short)0x000a       //PlayFX
#define          SID_ROCK                                         (unsigned short)0x000b       //ROCK
#define          SID_POP                                          (unsigned short)0x000c       //POP
#define          SID_CLASS                                        (unsigned short)0x000d       //CLASS
#define          SID_BASS                                         (unsigned short)0x000e       //BASS
#define          SID_JAZZ                                         (unsigned short)0x000f       //JAZZ
#define          SID_USER                                         (unsigned short)0x0010       //USER
#define          SID_UNKNOWN                                      (unsigned short)0x0011       //~Unknown~
#define          SID_NO_LYRIC_FILE                                (unsigned short)0x0012       //~No Lyric File~
#define          SID_MANUAL                                       (unsigned short)0x0013       //Manual
#define          SID_PRESET                                       (unsigned short)0x0014       //Preset
#define          SID_MEM                                          (unsigned short)0x0015       //Mem
#define          SID_DEL                                          (unsigned short)0x0016       //Del
#define          SID_AUTO                                         (unsigned short)0x0017       //Auto
#define          SID_SAVE_CHANNEL                                 (unsigned short)0x0018       //Save Channel?
#define          SID_DELETE_CHANNEL                               (unsigned short)0x0019       //Delete Channel?
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x001a       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x001b       //Load BookMark
#define          SID_MIC_REC                                      (unsigned short)0x001c       //MIC REC
#define          SID_LINE_IN_REC                                  (unsigned short)0x001d       //LINE IN REC
#define          SID_FM_REC                                       (unsigned short)0x001e       //FM REC
#define          SID_RECORDING                                    (unsigned short)0x001f       //Recording...
#define          SID_RECORD_PAUSE                                 (unsigned short)0x0020       //Pause...
#define          SID_RECORD_PREPARE                               (unsigned short)0x0021       //Prepare...
#define          SID_RECORD_SAVE_FILE                             (unsigned short)0x0022       //Save File...
#define          SID_CREAT_FILE_ERROR                             (unsigned short)0x0023       //Creat File Error!
#define          SID_DISK_IS_FULL                                 (unsigned short)0x0024       //Disk Is Full!
#define          SID_FLASH_MEMERY                                 (unsigned short)0x0025       //Flash Memery
#define          SID_MINISD_CARD                                  (unsigned short)0x0026       //MiniSD Card
#define          SID_WARNING                                      (unsigned short)0x0027       //Warning
#define          SID_YES                                          (unsigned short)0x0028       //Yes
#define          SID_NO                                           (unsigned short)0x0029       //No
#define          SID_EXIT                                         (unsigned short)0x002a       //Exit
#define          SID_PLEASE_WAIT                                  (unsigned short)0x002b       //Please Wait……
#define          SID_LOW_BATTERY                                  (unsigned short)0x002c       //Low Battery!
#define          SID_FIRMWARE_UPGRADE                             (unsigned short)0x002d       //Firmware Upgrade?
#define          SID_PLEASE_INSERT_USB                            (unsigned short)0x002e       //Connect USB……
#define          SID_RESTORE_DEFAULT_VAL                          (unsigned short)0x002f       //Restorable?
#define          SID_FORMAT_DISK                                  (unsigned short)0x0030       //Format Disk?
#define          SID_FORMATTING                                   (unsigned short)0x0031       //Formatting……
#define          SID_FILE_FORMAT_ERROR                            (unsigned short)0x0032       //File Format Error!
#define          SID_NO_MUSIC_FILE                                (unsigned short)0x0033       //No Music File!
#define          SID_DELETE_FILE                                  (unsigned short)0x0034       //Delete File
#define          SID_DELETE_FILE_ASK                              (unsigned short)0x0035       //Delete File?
#define          SID_DELETING_FILE                                (unsigned short)0x0036       //Deleting File……
#define          SID_MUSIC_FILE                                   (unsigned short)0x0037       //Music File
#define          SID_VIDEO_FILE                                   (unsigned short)0x0038       //Video File
#define          SID_TEXT_FILE                                    (unsigned short)0x0039       //Text
#define          SID_PICTURE_FILE                                 (unsigned short)0x003a       //Picture File
#define          SID_EXPLORER                                     (unsigned short)0x003b       //Explorer
#define          SID_C_FLASH                                      (unsigned short)0x003c       //C:FLASH
#define          SID_D_FLASH                                      (unsigned short)0x003d       //D:FLASH
#define          SID_D_SD_CARD                                    (unsigned short)0x003e       //D:SD CARD
#define          SID_E_SD_CARD                                    (unsigned short)0x003f       //E:SD CARD
#define          SID_NO_FILE                                      (unsigned short)0x0040       //No File!
#define          SID_SAVE_BOOKMARK                                (unsigned short)0x0041       //Save BookMark
#define          SID_LOAD_BOOKMARK                                (unsigned short)0x0042       //Load BookMark
#define          SID_WRITE_FILE_ERROR                             (unsigned short)0x0043       //Write File Error!
#define          SID_CLOSE_FILE_ERROR                             (unsigned short)0x0044       //Close File Error!
#define          SID_MEDIALIB                                     (unsigned short)0x0045       //medialib
#define          SID_PLAYING                                      (unsigned short)0x0046       //Current Play
#define          SID_ALL_MUISC_FILE                               (unsigned short)0x0047       //All Music
#define          SID_ARTIST                                       (unsigned short)0x0048       //Artist
#define          SID_TITLE                                        (unsigned short)0x0049       //Title
#define          SID_ALBUM                                        (unsigned short)0x004a       //Album
#define          SID_GENRE                                        (unsigned short)0x004b       //Genre
#define          SID_PLAY_LIST                                    (unsigned short)0x004c       //Playlist
#define          SID_DIR_LIST                                     (unsigned short)0x004d       //Directory listing
#define          SID_NET_RADIO                                    (unsigned short)0x004e       //NetRadio
#define          SID_RECORE_FILE                                  (unsigned short)0x004f       //RECORE FILE
#define          SID_MY_FAVORITE                                  (unsigned short)0x0050       //My Favorite
#define          SID_UPDATE_MEDIALIB                              (unsigned short)0x0051       //MediaLib Update
#define          SID_HOLDON_PLAY                                  (unsigned short)0x0052       //Breakpoint player
#define          SID_ADD_FAVORITE                                 (unsigned short)0x0053       //Add To Favorite
#define          SID_CLEAR_FAVORITE                               (unsigned short)0x0054       //Clear Up
#define          SID_UPDATEING_MEDIALIB                           (unsigned short)0x0055       //MediaLib Update……
#define          SID_SEARCH_WLAN                                  (unsigned short)0x0056       //Searching SSID
#define          SID_SEARCH_SSID                                  (unsigned short)0x0057       //SSID List
#define          SID_STATIONS                                     (unsigned short)0x0058       //Stations list
#define          SID_CONNECT_IP                                   (unsigned short)0x0059       //Conncting……
#define          SID_OK_CONNECT                                   (unsigned short)0x005a       //Connct Success!
#define          SID_NO_CONNECT                                   (unsigned short)0x005b       //Connct Failure!
#define          SID_GET_IP                                       (unsigned short)0x005c       //Get IP……
#define          SID_OK_IP                                        (unsigned short)0x005d       //Get IP Success!
#define          SID_NO_IP                                        (unsigned short)0x005e       //Get IP Failure!
#define          SID_INPUT_PW                                     (unsigned short)0x005f       //Password:
#define          SID_CLOSE_STATION                                (unsigned short)0x0060       //Closing Opened Station!
//-----------------------------------------------------------------------------------------------------------------------------
//-------This is a menu-------
#define          SID_SETTINGS                                     (unsigned short)0x0061       //Settings
#define          SID_SETTING_MUSIC                                (unsigned short)0x0062       //Music
#define          SID_MUSIC_REPEAT_MODE                            (unsigned short)0x0063       //Repeat Mode
#define          SID_MUSIC_ONCE                                   (unsigned short)0x0064       //Once                  [Function Index: 0000]
#define          SID_MUSIC_REPEAT_ONE                             (unsigned short)0x0065       //Repeat One            [Function Index: 0001]
#define          SID_MUSIC_FOLDER_ONCE                            (unsigned short)0x0066       //Folder Once           [Function Index: 0002]
#define          SID_MUSIC_FOLDER_REPEAT                          (unsigned short)0x0067       //Folder Repeat         [Function Index: 0003]
#define          SID_MUSIC_ALL_ONCE                               (unsigned short)0x0068       //All Once              [Function Index: 0004]
#define          SID_MUSIC_ALL_REPEAT                             (unsigned short)0x0069       //All Repeat            [Function Index: 0005]
#define          SID_MUSIC_INTRO                                  (unsigned short)0x006a       //Intro                 [Function Index: 0006]
#define          SID_MUSIC_PLAY_MODE                              (unsigned short)0x006b       //Play Mode
#define          SID_MUSIC_ORDER                                  (unsigned short)0x006c       //Order                 [Function Index: 0007]
#define          SID_MUSIC_SHUFFLE                                (unsigned short)0x006d       //Shuffle               [Function Index: 0008]
#define          SID_EQ_SELECT                                    (unsigned short)0x006e       //EQ Select
#define          SID_EQ_NORMAL                                    (unsigned short)0x006f       //Normal                [Function Index: 0009]
#define          SID_EQ_ROCK                                      (unsigned short)0x0070       //Rock                  [Function Index: 0010]
#define          SID_EQ_POP                                       (unsigned short)0x0071       //Pop                   [Function Index: 0011]
#define          SID_EQ_CLASSIC                                   (unsigned short)0x0072       //Classic               [Function Index: 0012]
#define          SID_EQ_BASS                                      (unsigned short)0x0073       //Bass                  [Function Index: 0013]
#define          SID_EQ_JAZZ                                      (unsigned short)0x0074       //Jazz                  [Function Index: 0014]
#define          SID_EQ_USER_EQ                                   (unsigned short)0x0075       //User EQ               [Function Index: 0015]
#define          SID_USER_EQ_SET                                  (unsigned short)0x0076       //User EQ Setting       [Function Index: 0016]
#define          SID_SETTING_RECORD                               (unsigned short)0x0077       //Record Settings
#define          SID_REC_QUALITY                                  (unsigned short)0x0078       //REC Quality
#define          SID_REC_HIGH_QUALITY                             (unsigned short)0x0079       //High Quality          [Function Index: 0017]
#define          SID_REC_NORMAL_QUALITY                           (unsigned short)0x007a       //Normal Quality        [Function Index: 0018]
#define          SID_SETTING_TEXT                                 (unsigned short)0x007b       //Text Settings
#define          SID_TEXT_AUTO_PLAY_TIME                          (unsigned short)0x007c       //Auto Play Time
#define          SID_TEXT_AUTO_PLAY_1S                            (unsigned short)0x007d       //2 s                   [Function Index: 0019]
#define          SID_TEXT_AUTO_PLAY_2S                            (unsigned short)0x007e       //4 s                   [Function Index: 0020]
#define          SID_TEXT_AUTO_PLAY_3S                            (unsigned short)0x007f       //6 s                   [Function Index: 0021]
#define          SID_TEXT_AUTO_PLAY_4S                            (unsigned short)0x0080       //8 s                   [Function Index: 0022]
#define          SID_TEXT_AUTO_PLAY_5S                            (unsigned short)0x0081       //10 s                  [Function Index: 0023]
#define          SID_SETTING_RADIO                                (unsigned short)0x0082       //Radio
#define          SID_RADIO_STEREO_SWITCH                          (unsigned short)0x0083       //Stereo Switch
#define          SID_STEREO_SWITCH_OFF                            (unsigned short)0x0084       //Off                   [Function Index: 0024]
#define          SID_STEREO_SWITCH_ON                             (unsigned short)0x0085       //On                    [Function Index: 0025]
#define          SID_FM_REGION                                    (unsigned short)0x0086       //FM Region
#define          SID_FM_REGION_CHINA                              (unsigned short)0x0087       //China                 [Function Index: 0026]
#define          SID_FM_REGION_EUROPE                             (unsigned short)0x0088       //Europe                [Function Index: 0027]
#define          SID_FM_REGION_JAPAN                              (unsigned short)0x0089       //Japan                 [Function Index: 0028]
#define          SID_FM_REGION_USA                                (unsigned short)0x008a       //U.S.A.                [Function Index: 0029]
#define          SID_SETTING_PIC                                  (unsigned short)0x008b       //Picture Settings
#define          SID_PIC_AUTO_PLAY_TIME                           (unsigned short)0x008c       //Auto Play Time
#define          SID_PIC_AUTO_PLAY_1S                             (unsigned short)0x008d       //2 s                   [Function Index: 0030]
#define          SID_PIC_AUTO_PLAY_2S                             (unsigned short)0x008e       //4 s                   [Function Index: 0031]
#define          SID_PIC_AUTO_PLAY_3S                             (unsigned short)0x008f       //6 s                   [Function Index: 0032]
#define          SID_PIC_AUTO_PLAY_4S                             (unsigned short)0x0090       //8 s                   [Function Index: 0033]
#define          SID_PIC_AUTO_PLAY_5S                             (unsigned short)0x0091       //10 s                  [Function Index: 0034]
#define          SID_SETTING_DISPLAY                              (unsigned short)0x0092       //Display
#define          SID_BLIGHT_TIME                                  (unsigned short)0x0093       //BLight Time
#define          SID_BLIGHT_TIME_5S                               (unsigned short)0x0094       //5  s                  [Function Index: 0035]
#define          SID_BLIGHT_TIME_10S                              (unsigned short)0x0095       //10 s                  [Function Index: 0036]
#define          SID_BLIGHT_TIME_15S                              (unsigned short)0x0096       //15 s                  [Function Index: 0037]
#define          SID_BLIGHT_TIME_20S                              (unsigned short)0x0097       //20 s                  [Function Index: 0038]
#define          SID_BLIGHT_TIME_30S                              (unsigned short)0x0098       //30 s                  [Function Index: 0039]
#define          SID_BLIGHT_TIME_ALWAYS_ON                        (unsigned short)0x0099       //Always On             [Function Index: 0040]
#define          SID_SETTING_LUM                                  (unsigned short)0x009a       //Lum
#define          SID_LUM_1                                        (unsigned short)0x009b       //1                     [Function Index: 0041]
#define          SID_LUM_2                                        (unsigned short)0x009c       //2                     [Function Index: 0042]
#define          SID_LUM_3                                        (unsigned short)0x009d       //3                     [Function Index: 0043]
#define          SID_LUM_4                                        (unsigned short)0x009e       //4                     [Function Index: 0044]
#define          SID_LUM_5                                        (unsigned short)0x009f       //5                     [Function Index: 0045]
#define          SID_BLIGHT_MODE                                  (unsigned short)0x00a0       //BLight Mode
#define          SID_BLIGHT_MODE_NORMAL                           (unsigned short)0x00a1       //Normal                [Function Index: 0046]
#define          SID_BLIGHT_MODE_PWR_SAVE                         (unsigned short)0x00a2       //Power Save            [Function Index: 0047]
#define          SID_POWER_OFF                                    (unsigned short)0x00a3       //Power Off
#define          SID_POWER_OFF_OFF                                (unsigned short)0x00a4       //OFF                   [Function Index: 0048]
#define          SID_PWR_OFF_10_MIN                               (unsigned short)0x00a5       //10  Minute            [Function Index: 0049]
#define          SID_PWR_OFF_15_MIN                               (unsigned short)0x00a6       //15  Minute            [Function Index: 0050]
#define          SID_PWR_OFF_30_MIN                               (unsigned short)0x00a7       //30  Minute            [Function Index: 0051]
#define          SID_PWR_OFF_60_MIN                               (unsigned short)0x00a8       //60  Minute            [Function Index: 0052]
#define          SID_PWR_OFF_120_MIN                              (unsigned short)0x00a9       //120 Minute            [Function Index: 0053]
#define          SID_LANGUAGE                                     (unsigned short)0x00aa       //Language
#define          SID_CHINESE_S                                    (unsigned short)0x00ab       //简体中文              [Function Index: 0054]
#define          SID_CHINESE_T                                    (unsigned short)0x00ac       //繁體中文              [Function Index: 0055]
#define          SID_ENGLISH                                      (unsigned short)0x00ad       //English               [Function Index: 0056]
#define          SID_KOREAN                                       (unsigned short)0x00ae       //??                    [Function Index: 0057]
#define          SID_JAPANESE                                     (unsigned short)0x00af       //日本語                [Function Index: 0058]
#define          SID_SPANISH                                      (unsigned short)0x00b0       //Spanish               [Function Index: 0059]
#define          SID_FRENCH                                       (unsigned short)0x00b1       //Fran?ais              [Function Index: 0060]
#define          SID_GERMAN                                       (unsigned short)0x00b2       //Deutsch               [Function Index: 0061]
#define          SID_ITALIAN                                      (unsigned short)0x00b3       //Italiano              [Function Index: 0062]
#define          SID_PORTUGUESE                                   (unsigned short)0x00b4       //Português            [Function Index: 0063]
#define          SID_RUSSIAN                                      (unsigned short)0x00b5       //Русский        [Function Index: 0064]
#define          SID_SWEDISH                                      (unsigned short)0x00b6       //Svenska               [Function Index: 0065]
#define          SID_THAI                                         (unsigned short)0x00b7       //???????               [Function Index: 0066]
#define          SID_POLISH                                       (unsigned short)0x00b8       //j?zyk polski          [Function Index: 0067]
#define          SID_DENISH                                       (unsigned short)0x00b9       //Dansk                 [Function Index: 0068]
#define          SID_HOLLANDS                                     (unsigned short)0x00ba       //Hollands              [Function Index: 0069]
#define          SID_GREEK                                        (unsigned short)0x00bb       //Ελληνικ?       [Function Index: 0070]
#define          SID_CZECHIC                                      (unsigned short)0x00bc       //?í?tina              [Function Index: 0071]
#define          SID_TURKISH                                      (unsigned short)0x00bd       //Türk?e               [Function Index: 0072]
#define          SID_HEBREW                                       (unsigned short)0x00be       //?????, ????           [Function Index: 0073]
#define          SID_ARABIC                                       (unsigned short)0x00bf       //Arabic                [Function Index: 0074]
#define          SID_SETTING_SYSTEM                               (unsigned short)0x00c0       //System
#define          SID_SYS_ABOUT                                    (unsigned short)0x00c1       //About                 [Function Index: 0075]
#define          SID_SYS_UPGRADE                                  (unsigned short)0x00c2       //Upgrade               [Function Index: 0076]
#define          SID_SYS_DEFAULT_SET                              (unsigned short)0x00c3       //Default Set           [Function Index: 0077]
#define          SID_EXIT_SYS_SETTING                             (unsigned short)0x00c4       //Exit Setting          [Function Index: 0078]





//-----------------------------------------------------------------------------------------------------------------------------
#define          SID_SETTINGS_ENTRY                               SID_SETTINGS       //Settings
#define          SID_SETTINGS_ENTRY_FUN_COUNTER                   0x004f


#endif
