/********************************************************************
 This file was generated by ImageConvert Tool of Rockchip Co., Ltd.

 Generate time: 2015-3-28 11:50:39

 Tool Version: 3.0.0.0

 End.
********************************************************************/
#ifndef       _IMAGERESOURCE_H_
#define       _IMAGERESOURCE_H_


#define        IMAGE_IN_FLASH_BASE_ADDR                          (unsigned long)0

#define        IMG_POWERON0                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1360)
#define        IMG_POWERON0_WIDTH                                    128
#define        IMG_POWERON0_HEIGTH                                   160
#define        IMG_POWERON0_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON1                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xb360)
#define        IMG_POWERON1_WIDTH                                    128
#define        IMG_POWERON1_HEIGTH                                   160
#define        IMG_POWERON1_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON2                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x15360)
#define        IMG_POWERON2_WIDTH                                    128
#define        IMG_POWERON2_HEIGTH                                   160
#define        IMG_POWERON2_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON3                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1f360)
#define        IMG_POWERON3_WIDTH                                    128
#define        IMG_POWERON3_HEIGTH                                   160
#define        IMG_POWERON3_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON4                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x29360)
#define        IMG_POWERON4_WIDTH                                    128
#define        IMG_POWERON4_HEIGTH                                   160
#define        IMG_POWERON4_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON5                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x33360)
#define        IMG_POWERON5_WIDTH                                    128
#define        IMG_POWERON5_HEIGTH                                   160
#define        IMG_POWERON5_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON6                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x3d360)
#define        IMG_POWERON6_WIDTH                                    128
#define        IMG_POWERON6_HEIGTH                                   160
#define        IMG_POWERON6_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON7                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x47360)
#define        IMG_POWERON7_WIDTH                                    128
#define        IMG_POWERON7_HEIGTH                                   160
#define        IMG_POWERON7_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON8                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x51360)
#define        IMG_POWERON8_WIDTH                                    128
#define        IMG_POWERON8_HEIGTH                                   160
#define        IMG_POWERON8_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON9                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x5b360)
#define        IMG_POWERON9_WIDTH                                    128
#define        IMG_POWERON9_HEIGTH                                   160
#define        IMG_POWERON9_SIZE                                     (unsigned long)0xa000

#define        IMG_POWERON10                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x65360)
#define        IMG_POWERON10_WIDTH                                   128
#define        IMG_POWERON10_HEIGTH                                  160
#define        IMG_POWERON10_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON11                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x6f360)
#define        IMG_POWERON11_WIDTH                                   128
#define        IMG_POWERON11_HEIGTH                                  160
#define        IMG_POWERON11_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON12                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x79360)
#define        IMG_POWERON12_WIDTH                                   128
#define        IMG_POWERON12_HEIGTH                                  160
#define        IMG_POWERON12_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON13                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x83360)
#define        IMG_POWERON13_WIDTH                                   128
#define        IMG_POWERON13_HEIGTH                                  160
#define        IMG_POWERON13_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON14                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x8d360)
#define        IMG_POWERON14_WIDTH                                   128
#define        IMG_POWERON14_HEIGTH                                  160
#define        IMG_POWERON14_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON15                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x97360)
#define        IMG_POWERON15_WIDTH                                   128
#define        IMG_POWERON15_HEIGTH                                  160
#define        IMG_POWERON15_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON16                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xa1360)
#define        IMG_POWERON16_WIDTH                                   128
#define        IMG_POWERON16_HEIGTH                                  160
#define        IMG_POWERON16_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON17                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xab360)
#define        IMG_POWERON17_WIDTH                                   128
#define        IMG_POWERON17_HEIGTH                                  160
#define        IMG_POWERON17_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON18                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xb5360)
#define        IMG_POWERON18_WIDTH                                   128
#define        IMG_POWERON18_HEIGTH                                  160
#define        IMG_POWERON18_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON19                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xbf360)
#define        IMG_POWERON19_WIDTH                                   128
#define        IMG_POWERON19_HEIGTH                                  160
#define        IMG_POWERON19_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON20                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xc9360)
#define        IMG_POWERON20_WIDTH                                   128
#define        IMG_POWERON20_HEIGTH                                  160
#define        IMG_POWERON20_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON21                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xd3360)
#define        IMG_POWERON21_WIDTH                                   128
#define        IMG_POWERON21_HEIGTH                                  160
#define        IMG_POWERON21_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON22                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xdd360)
#define        IMG_POWERON22_WIDTH                                   128
#define        IMG_POWERON22_HEIGTH                                  160
#define        IMG_POWERON22_SIZE                                    (unsigned long)0xa000

#define        IMG_POWERON23                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xe7360)
#define        IMG_POWERON23_WIDTH                                   128
#define        IMG_POWERON23_HEIGTH                                  160
#define        IMG_POWERON23_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF0                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xf1360)
#define        IMG_POWEROFF0_WIDTH                                   128
#define        IMG_POWEROFF0_HEIGTH                                  160
#define        IMG_POWEROFF0_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF1                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0xfb360)
#define        IMG_POWEROFF1_WIDTH                                   128
#define        IMG_POWEROFF1_HEIGTH                                  160
#define        IMG_POWEROFF1_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF2                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x105360)
#define        IMG_POWEROFF2_WIDTH                                   128
#define        IMG_POWEROFF2_HEIGTH                                  160
#define        IMG_POWEROFF2_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF3                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x10f360)
#define        IMG_POWEROFF3_WIDTH                                   128
#define        IMG_POWEROFF3_HEIGTH                                  160
#define        IMG_POWEROFF3_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF4                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x119360)
#define        IMG_POWEROFF4_WIDTH                                   128
#define        IMG_POWEROFF4_HEIGTH                                  160
#define        IMG_POWEROFF4_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF5                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x123360)
#define        IMG_POWEROFF5_WIDTH                                   128
#define        IMG_POWEROFF5_HEIGTH                                  160
#define        IMG_POWEROFF5_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF6                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x12d360)
#define        IMG_POWEROFF6_WIDTH                                   128
#define        IMG_POWEROFF6_HEIGTH                                  160
#define        IMG_POWEROFF6_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF7                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x137360)
#define        IMG_POWEROFF7_WIDTH                                   128
#define        IMG_POWEROFF7_HEIGTH                                  160
#define        IMG_POWEROFF7_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF8                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x141360)
#define        IMG_POWEROFF8_WIDTH                                   128
#define        IMG_POWEROFF8_HEIGTH                                  160
#define        IMG_POWEROFF8_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF9                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x14b360)
#define        IMG_POWEROFF9_WIDTH                                   128
#define        IMG_POWEROFF9_HEIGTH                                  160
#define        IMG_POWEROFF9_SIZE                                    (unsigned long)0xa000

#define        IMG_POWEROFF10                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x155360)
#define        IMG_POWEROFF10_WIDTH                                  128
#define        IMG_POWEROFF10_HEIGTH                                 160
#define        IMG_POWEROFF10_SIZE                                   (unsigned long)0xa000

#define        IMG_POWEROFF11                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x15f360)
#define        IMG_POWEROFF11_WIDTH                                  128
#define        IMG_POWEROFF11_HEIGTH                                 160
#define        IMG_POWEROFF11_SIZE                                   (unsigned long)0xa000

#define        IMG_USB_BACKGROUND                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x169360)
#define        IMG_USB_BACKGROUND_WIDTH                              128
#define        IMG_USB_BACKGROUND_HEIGTH                             160
#define        IMG_USB_BACKGROUND_SIZE                               (unsigned long)0xa000

#define        IMG_CHARGELEVEL0                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x173360)
#define        IMG_CHARGELEVEL0_WIDTH                                128
#define        IMG_CHARGELEVEL0_HEIGTH                               160
#define        IMG_CHARGELEVEL0_SIZE                                 (unsigned long)0xa000

#define        IMG_CHARGELEVEL1                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x17d360)
#define        IMG_CHARGELEVEL1_WIDTH                                128
#define        IMG_CHARGELEVEL1_HEIGTH                               160
#define        IMG_CHARGELEVEL1_SIZE                                 (unsigned long)0xa000

#define        IMG_CHARGELEVEL2                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x187360)
#define        IMG_CHARGELEVEL2_WIDTH                                128
#define        IMG_CHARGELEVEL2_HEIGTH                               160
#define        IMG_CHARGELEVEL2_SIZE                                 (unsigned long)0xa000

#define        IMG_CHARGELEVEL3                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x191360)
#define        IMG_CHARGELEVEL3_WIDTH                                128
#define        IMG_CHARGELEVEL3_HEIGTH                               160
#define        IMG_CHARGELEVEL3_SIZE                                 (unsigned long)0xa000

#define        IMG_CHARGELEVEL4                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x19b360)
#define        IMG_CHARGELEVEL4_WIDTH                                128
#define        IMG_CHARGELEVEL4_HEIGTH                               160
#define        IMG_CHARGELEVEL4_SIZE                                 (unsigned long)0xa000

#define        IMG_MESSAGEBOX_BACKGROUND                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1a5360)
#define        IMG_MESSAGEBOX_BACKGROUND_WIDTH                       100
#define        IMG_MESSAGEBOX_BACKGROUND_HEIGTH                      80
#define        IMG_MESSAGEBOX_BACKGROUND_SIZE                        (unsigned long)0x3e80

#define        IMG_DIALOGBOX_BACKGROUND                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1a91e0)
#define        IMG_DIALOGBOX_BACKGROUND_WIDTH                        100
#define        IMG_DIALOGBOX_BACKGROUND_HEIGTH                       80
#define        IMG_DIALOGBOX_BACKGROUND_SIZE                         (unsigned long)0x3e80

#define        IMG_DIALOGBOX_BUTTONNO                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1ad060)
#define        IMG_DIALOGBOX_BUTTONNO_WIDTH                          92
#define        IMG_DIALOGBOX_BUTTONNO_HEIGTH                         21
#define        IMG_DIALOGBOX_BUTTONNO_SIZE                           (unsigned long)0xf18

#define        IMG_DIALOGBOX_BUTTONYES                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1adf78)
#define        IMG_DIALOGBOX_BUTTONYES_WIDTH                         92
#define        IMG_DIALOGBOX_BUTTONYES_HEIGTH                        21
#define        IMG_DIALOGBOX_BUTTONYES_SIZE                          (unsigned long)0xf18

#define        IMG_LOWPOWER                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1aee90)
#define        IMG_LOWPOWER_WIDTH                                    96
#define        IMG_LOWPOWER_HEIGTH                                   64
#define        IMG_LOWPOWER_SIZE                                     (unsigned long)0x3000

#define        IMG_MAINMENU_MUSIC                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1b1e90)
#define        IMG_MAINMENU_MUSIC_WIDTH                              128
#define        IMG_MAINMENU_MUSIC_HEIGTH                             160
#define        IMG_MAINMENU_MUSIC_SIZE                               (unsigned long)0xa000

#define        IMG_MAINMENU_VEDIO                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1bbe90)
#define        IMG_MAINMENU_VEDIO_WIDTH                              128
#define        IMG_MAINMENU_VEDIO_HEIGTH                             160
#define        IMG_MAINMENU_VEDIO_SIZE                               (unsigned long)0xa000

#define        IMG_MAINMENU_FM                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1c5e90)
#define        IMG_MAINMENU_FM_WIDTH                                 128
#define        IMG_MAINMENU_FM_HEIGTH                                160
#define        IMG_MAINMENU_FM_SIZE                                  (unsigned long)0xa000

#define        IMG_MAINMENU_PHOTO                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1cfe90)
#define        IMG_MAINMENU_PHOTO_WIDTH                              128
#define        IMG_MAINMENU_PHOTO_HEIGTH                             160
#define        IMG_MAINMENU_PHOTO_SIZE                               (unsigned long)0xa000

#define        IMG_MAINMENU_BOOK                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1d9e90)
#define        IMG_MAINMENU_BOOK_WIDTH                               128
#define        IMG_MAINMENU_BOOK_HEIGTH                              160
#define        IMG_MAINMENU_BOOK_SIZE                                (unsigned long)0xa000

#define        IMG_MAINMENU_RECOD                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1e3e90)
#define        IMG_MAINMENU_RECOD_WIDTH                              128
#define        IMG_MAINMENU_RECOD_HEIGTH                             160
#define        IMG_MAINMENU_RECOD_SIZE                               (unsigned long)0xa000

#define        IMG_MAINMENU_BROWSER                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1ede90)
#define        IMG_MAINMENU_BROWSER_WIDTH                            128
#define        IMG_MAINMENU_BROWSER_HEIGTH                           160
#define        IMG_MAINMENU_BROWSER_SIZE                             (unsigned long)0xa000

#define        IMG_MAINMENU_GAME                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x1f7e90)
#define        IMG_MAINMENU_GAME_WIDTH                               128
#define        IMG_MAINMENU_GAME_HEIGTH                              160
#define        IMG_MAINMENU_GAME_SIZE                                (unsigned long)0xa000

#define        IMG_MAINMENU_SETMENU                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x201e90)
#define        IMG_MAINMENU_SETMENU_WIDTH                            128
#define        IMG_MAINMENU_SETMENU_HEIGTH                           160
#define        IMG_MAINMENU_SETMENU_SIZE                             (unsigned long)0xa000

#define        IMG_MUSIC_BACKGROUND                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x20be90)
#define        IMG_MUSIC_BACKGROUND_WIDTH                            128
#define        IMG_MUSIC_BACKGROUND_HEIGTH                           160
#define        IMG_MUSIC_BACKGROUND_SIZE                             (unsigned long)0xa000

#define        IMG_MUSIC_BACKGROUND1                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x215e90)
#define        IMG_MUSIC_BACKGROUND1_WIDTH                           128
#define        IMG_MUSIC_BACKGROUND1_HEIGTH                          160
#define        IMG_MUSIC_BACKGROUND1_SIZE                            (unsigned long)0xa000

#define        IMG_MUSIC_BPSICON                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x21fe90)
#define        IMG_MUSIC_BPSICON_WIDTH                               20
#define        IMG_MUSIC_BPSICON_HEIGTH                              7
#define        IMG_MUSIC_BPSICON_SIZE                                (unsigned long)0x118

#define        IMG_MUSIC_BPSBACKGROND                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x21ffa8)
#define        IMG_MUSIC_BPSBACKGROND_WIDTH                          5
#define        IMG_MUSIC_BPSBACKGROND_HEIGTH                         5
#define        IMG_MUSIC_BPSBACKGROND_SIZE                           (unsigned long)0x32

#define        IMG_MUSIC_PLAY_STATE                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x21ffda)
#define        IMG_MUSIC_PLAY_STATE_WIDTH                            16
#define        IMG_MUSIC_PLAY_STATE_HEIGTH                           16
#define        IMG_MUSIC_PLAY_STATE_SIZE                             (unsigned long)0x200

#define        IMG_MUSIC_PAUSE_STATE                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2201da)
#define        IMG_MUSIC_PAUSE_STATE_WIDTH                           16
#define        IMG_MUSIC_PAUSE_STATE_HEIGTH                          16
#define        IMG_MUSIC_PAUSE_STATE_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_CURRTIME_BACK                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2203da)
#define        IMG_MUSIC_CURRTIME_BACK_WIDTH                         60
#define        IMG_MUSIC_CURRTIME_BACK_HEIGTH                        12
#define        IMG_MUSIC_CURRTIME_BACK_SIZE                          (unsigned long)0x5a0

#define        IMG_MUSIC_LOOP_MODE01                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22097a)
#define        IMG_MUSIC_LOOP_MODE01_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE01_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE01_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_LOOP_MODE02                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x220b7a)
#define        IMG_MUSIC_LOOP_MODE02_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE02_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE02_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_LOOP_MODE03                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x220d7a)
#define        IMG_MUSIC_LOOP_MODE03_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE03_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE03_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_LOOP_MODE04                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x220f7a)
#define        IMG_MUSIC_LOOP_MODE04_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE04_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE04_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_LOOP_MODE05                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22117a)
#define        IMG_MUSIC_LOOP_MODE05_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE05_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE05_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_LOOP_MODE06                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22137a)
#define        IMG_MUSIC_LOOP_MODE06_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE06_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE06_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_LOOP_MODE07                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22157a)
#define        IMG_MUSIC_LOOP_MODE07_WIDTH                           16
#define        IMG_MUSIC_LOOP_MODE07_HEIGTH                          16
#define        IMG_MUSIC_LOOP_MODE07_SIZE                            (unsigned long)0x200

#define        IMG_MUSIC_ORDER_MODE01                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22177a)
#define        IMG_MUSIC_ORDER_MODE01_WIDTH                          16
#define        IMG_MUSIC_ORDER_MODE01_HEIGTH                         16
#define        IMG_MUSIC_ORDER_MODE01_SIZE                           (unsigned long)0x200

#define        IMG_MUSIC_ORDER_MODE02                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22197a)
#define        IMG_MUSIC_ORDER_MODE02_WIDTH                          16
#define        IMG_MUSIC_ORDER_MODE02_HEIGTH                         16
#define        IMG_MUSIC_ORDER_MODE02_SIZE                           (unsigned long)0x200

#define        IMG_MUSIC_A_B_MODE_BACK                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x221b7a)
#define        IMG_MUSIC_A_B_MODE_BACK_WIDTH                         24
#define        IMG_MUSIC_A_B_MODE_BACK_HEIGTH                        12
#define        IMG_MUSIC_A_B_MODE_BACK_SIZE                          (unsigned long)0x240

#define        IMG_MUSIC_A_MODE                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x221dba)
#define        IMG_MUSIC_A_MODE_WIDTH                                24
#define        IMG_MUSIC_A_MODE_HEIGTH                               12
#define        IMG_MUSIC_A_MODE_SIZE                                 (unsigned long)0x240

#define        IMG_MUSIC_A_B_MODE                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x221ffa)
#define        IMG_MUSIC_A_B_MODE_WIDTH                              24
#define        IMG_MUSIC_A_B_MODE_HEIGTH                             12
#define        IMG_MUSIC_A_B_MODE_SIZE                               (unsigned long)0x240

#define        IMG_MUSIC_BATTERY01                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22223a)
#define        IMG_MUSIC_BATTERY01_WIDTH                             20
#define        IMG_MUSIC_BATTERY01_HEIGTH                            12
#define        IMG_MUSIC_BATTERY01_SIZE                              (unsigned long)0x1e0

#define        IMG_MUSIC_BATTERY02                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22241a)
#define        IMG_MUSIC_BATTERY02_WIDTH                             20
#define        IMG_MUSIC_BATTERY02_HEIGTH                            12
#define        IMG_MUSIC_BATTERY02_SIZE                              (unsigned long)0x1e0

#define        IMG_MUSIC_BATTERY03                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2225fa)
#define        IMG_MUSIC_BATTERY03_WIDTH                             20
#define        IMG_MUSIC_BATTERY03_HEIGTH                            12
#define        IMG_MUSIC_BATTERY03_SIZE                              (unsigned long)0x1e0

#define        IMG_MUSIC_BATTERY04                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2227da)
#define        IMG_MUSIC_BATTERY04_WIDTH                             20
#define        IMG_MUSIC_BATTERY04_HEIGTH                            12
#define        IMG_MUSIC_BATTERY04_SIZE                              (unsigned long)0x1e0

#define        IMG_MUSIC_BATTERY04                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2229ba)
#define        IMG_MUSIC_BATTERY04_WIDTH                             20
#define        IMG_MUSIC_BATTERY04_HEIGTH                            12
#define        IMG_MUSIC_BATTERY04_SIZE                              (unsigned long)0x1e0

#define        IMG_MUSIC_NAMEBK                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x222b9a)
#define        IMG_MUSIC_NAMEBK_WIDTH                                100
#define        IMG_MUSIC_NAMEBK_HEIGTH                               16
#define        IMG_MUSIC_NAMEBK_SIZE                                 (unsigned long)0xc80

#define        IMG_MUSIC_ID3MANE                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22381a)
#define        IMG_MUSIC_ID3MANE_WIDTH                               124
#define        IMG_MUSIC_ID3MANE_HEIGTH                              52
#define        IMG_MUSIC_ID3MANE_SIZE                                (unsigned long)0x3260

#define        IMG_MUSIC_KBPSBK                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x226a7a)
#define        IMG_MUSIC_KBPSBK_WIDTH                                60
#define        IMG_MUSIC_KBPSBK_HEIGTH                               12
#define        IMG_MUSIC_KBPSBK_SIZE                                 (unsigned long)0x5a0

#define        IMG_MUSIC_NUMBER                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22701a)
#define        IMG_MUSIC_NUMBER_WIDTH                                60
#define        IMG_MUSIC_NUMBER_HEIGTH                               12
#define        IMG_MUSIC_NUMBER_SIZE                                 (unsigned long)0x5a0

#define        IMG_MUSIC_SPECTRUM20                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2275ba)
#define        IMG_MUSIC_SPECTRUM20_WIDTH                            7
#define        IMG_MUSIC_SPECTRUM20_HEIGTH                           35
#define        IMG_MUSIC_SPECTRUM20_SIZE                             (unsigned long)0x1ea

#define        IMG_MUSIC_SMALLLOCK                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2277a4)
#define        IMG_MUSIC_SMALLLOCK_WIDTH                             12
#define        IMG_MUSIC_SMALLLOCK_HEIGTH                            12
#define        IMG_MUSIC_SMALLLOCK_SIZE                              (unsigned long)0x120

#define        IMG_MUSIC_SMALLLOCK_BACK                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2278c4)
#define        IMG_MUSIC_SMALLLOCK_BACK_WIDTH                        12
#define        IMG_MUSIC_SMALLLOCK_BACK_HEIGTH                       12
#define        IMG_MUSIC_SMALLLOCK_BACK_SIZE                         (unsigned long)0x120

#define        IMG_VIDEO_PAUSE                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2279e4)
#define        IMG_VIDEO_PAUSE_WIDTH                                 15
#define        IMG_VIDEO_PAUSE_HEIGTH                                15
#define        IMG_VIDEO_PAUSE_SIZE                                  (unsigned long)0x1c2

#define        IMG_VIDEO_PLAY                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x227ba6)
#define        IMG_VIDEO_PLAY_WIDTH                                  15
#define        IMG_VIDEO_PLAY_HEIGTH                                 15
#define        IMG_VIDEO_PLAY_SIZE                                   (unsigned long)0x1c2

#define        IMG_VEDIO_STAUT_PLAY                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x227d68)
#define        IMG_VEDIO_STAUT_PLAY_WIDTH                            16
#define        IMG_VEDIO_STAUT_PLAY_HEIGTH                           16
#define        IMG_VEDIO_STAUT_PLAY_SIZE                             (unsigned long)0x200

#define        IMG_VEDIO_STAUT_PAUSE                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x227f68)
#define        IMG_VEDIO_STAUT_PAUSE_WIDTH                           16
#define        IMG_VEDIO_STAUT_PAUSE_HEIGTH                          16
#define        IMG_VEDIO_STAUT_PAUSE_SIZE                            (unsigned long)0x200

#define        IMG_VEDIO_STAUT_STIP                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x228168)
#define        IMG_VEDIO_STAUT_STIP_WIDTH                            16
#define        IMG_VEDIO_STAUT_STIP_HEIGTH                           16
#define        IMG_VEDIO_STAUT_STIP_SIZE                             (unsigned long)0x200

#define        IMG_VEDIO_VOLUME_BACK                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x228368)
#define        IMG_VEDIO_VOLUME_BACK_WIDTH                           12
#define        IMG_VEDIO_VOLUME_BACK_HEIGTH                          12
#define        IMG_VEDIO_VOLUME_BACK_SIZE                            (unsigned long)0x120

#define        IMG_VEDIO_TIME_BACK                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x228488)
#define        IMG_VEDIO_TIME_BACK_WIDTH                             50
#define        IMG_VEDIO_TIME_BACK_HEIGTH                            12
#define        IMG_VEDIO_TIME_BACK_SIZE                              (unsigned long)0x4b0

#define        IMG_VEDIO_DOWNBACKGROUND                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x228938)
#define        IMG_VEDIO_DOWNBACKGROUND_WIDTH                        160
#define        IMG_VEDIO_DOWNBACKGROUND_HEIGTH                       17
#define        IMG_VEDIO_DOWNBACKGROUND_SIZE                         (unsigned long)0x1540

#define        IMG_VEDIO_ICON                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x229e78)
#define        IMG_VEDIO_ICON_WIDTH                                  16
#define        IMG_VEDIO_ICON_HEIGTH                                 16
#define        IMG_VEDIO_ICON_SIZE                                   (unsigned long)0x200

#define        IMG_VEDIO_NOVOL                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22a078)
#define        IMG_VEDIO_NOVOL_WIDTH                                 12
#define        IMG_VEDIO_NOVOL_HEIGTH                                12
#define        IMG_VEDIO_NOVOL_SIZE                                  (unsigned long)0x120

#define        IMG_VEDIO_UPBACKGROUND                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22a198)
#define        IMG_VEDIO_UPBACKGROUND_WIDTH                          160
#define        IMG_VEDIO_UPBACKGROUND_HEIGTH                         17
#define        IMG_VEDIO_UPBACKGROUND_SIZE                           (unsigned long)0x1540

#define        IMG_VIDEO_SMALLLOCK                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22b6d8)
#define        IMG_VIDEO_SMALLLOCK_WIDTH                             12
#define        IMG_VIDEO_SMALLLOCK_HEIGTH                            12
#define        IMG_VIDEO_SMALLLOCK_SIZE                              (unsigned long)0x120

#define        IMG_VIDEO_SMALLLOCK_BACK                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22b7f8)
#define        IMG_VIDEO_SMALLLOCK_BACK_WIDTH                        12
#define        IMG_VIDEO_SMALLLOCK_BACK_HEIGTH                       12
#define        IMG_VIDEO_SMALLLOCK_BACK_SIZE                         (unsigned long)0x120

#define        IMG_VIDEO_BATTERY01                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22b918)
#define        IMG_VIDEO_BATTERY01_WIDTH                             20
#define        IMG_VIDEO_BATTERY01_HEIGTH                            12
#define        IMG_VIDEO_BATTERY01_SIZE                              (unsigned long)0x1e0

#define        IMG_VIDEO_BATTERY02                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22baf8)
#define        IMG_VIDEO_BATTERY02_WIDTH                             20
#define        IMG_VIDEO_BATTERY02_HEIGTH                            12
#define        IMG_VIDEO_BATTERY02_SIZE                              (unsigned long)0x1e0

#define        IMG_VIDEO_BATTERY03                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22bcd8)
#define        IMG_VIDEO_BATTERY03_WIDTH                             20
#define        IMG_VIDEO_BATTERY03_HEIGTH                            12
#define        IMG_VIDEO_BATTERY03_SIZE                              (unsigned long)0x1e0

#define        IMG_VIDEO_BATTERY04                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22beb8)
#define        IMG_VIDEO_BATTERY04_WIDTH                             20
#define        IMG_VIDEO_BATTERY04_HEIGTH                            12
#define        IMG_VIDEO_BATTERY04_SIZE                              (unsigned long)0x1e0

#define        IMG_VIDEO_BATTERY04                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22c098)
#define        IMG_VIDEO_BATTERY04_WIDTH                             20
#define        IMG_VIDEO_BATTERY04_HEIGTH                            12
#define        IMG_VIDEO_BATTERY04_SIZE                              (unsigned long)0x1e0

#define        IMG_RADIO_SCHEDU                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22c278)
#define        IMG_RADIO_SCHEDU_WIDTH                                7
#define        IMG_RADIO_SCHEDU_HEIGTH                               4
#define        IMG_RADIO_SCHEDU_SIZE                                 (unsigned long)0x38

#define        IMG_RADIO_VOLBACKGROUNDGREEN                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22c2b0)
#define        IMG_RADIO_VOLBACKGROUNDGREEN_WIDTH                    18
#define        IMG_RADIO_VOLBACKGROUNDGREEN_HEIGTH                   14
#define        IMG_RADIO_VOLBACKGROUNDGREEN_SIZE                     (unsigned long)0x1f8

#define        IMG_RADIO_VOLBACKGROUNDRED                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22c4a8)
#define        IMG_RADIO_VOLBACKGROUNDRED_WIDTH                      18
#define        IMG_RADIO_VOLBACKGROUNDRED_HEIGTH                     14
#define        IMG_RADIO_VOLBACKGROUNDRED_SIZE                       (unsigned long)0x1f8

#define        IMG_RADIO_MENUBACKGROUND                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22c6a0)
#define        IMG_RADIO_MENUBACKGROUND_WIDTH                        66
#define        IMG_RADIO_MENUBACKGROUND_HEIGTH                       84
#define        IMG_RADIO_MENUBACKGROUND_SIZE                         (unsigned long)0x2b50

#define        IMG_RADIO_MENUARROWBK                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22f1f0)
#define        IMG_RADIO_MENUARROWBK_WIDTH                           12
#define        IMG_RADIO_MENUARROWBK_HEIGTH                          12
#define        IMG_RADIO_MENUARROWBK_SIZE                            (unsigned long)0x120

#define        IMG_RADIO_MENUARROW                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22f310)
#define        IMG_RADIO_MENUARROW_WIDTH                             12
#define        IMG_RADIO_MENUARROW_HEIGTH                            12
#define        IMG_RADIO_MENUARROW_SIZE                              (unsigned long)0x120

#define        IMG_RADIO_STOREBACKGROUND                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x22f430)
#define        IMG_RADIO_STOREBACKGROUND_WIDTH                       80
#define        IMG_RADIO_STOREBACKGROUND_HEIGTH                      55
#define        IMG_RADIO_STOREBACKGROUND_SIZE                        (unsigned long)0x2260

#define        IMG_RADIO_STORE_UPARROWBK                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x231690)
#define        IMG_RADIO_STORE_UPARROWBK_WIDTH                       7
#define        IMG_RADIO_STORE_UPARROWBK_HEIGTH                      6
#define        IMG_RADIO_STORE_UPARROWBK_SIZE                        (unsigned long)0x54

#define        IMG_RADIO_STORE_UPARROW                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2316e4)
#define        IMG_RADIO_STORE_UPARROW_WIDTH                         7
#define        IMG_RADIO_STORE_UPARROW_HEIGTH                        6
#define        IMG_RADIO_STORE_UPARROW_SIZE                          (unsigned long)0x54

#define        IMG_RADIO_STOREDOWNARROWBK                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x231738)
#define        IMG_RADIO_STOREDOWNARROWBK_WIDTH                      7
#define        IMG_RADIO_STOREDOWNARROWBK_HEIGTH                     6
#define        IMG_RADIO_STOREDOWNARROWBK_SIZE                       (unsigned long)0x54

#define        IMG_RADIO_STOREDOWNARROW                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x23178c)
#define        IMG_RADIO_STOREDOWNARROW_WIDTH                        7
#define        IMG_RADIO_STOREDOWNARROW_HEIGTH                       6
#define        IMG_RADIO_STOREDOWNARROW_SIZE                         (unsigned long)0x54

#define        IMG_RADIO_FREQLISTBACKGROUND                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2317e0)
#define        IMG_RADIO_FREQLISTBACKGROUND_WIDTH                    80
#define        IMG_RADIO_FREQLISTBACKGROUND_HEIGTH                   55
#define        IMG_RADIO_FREQLISTBACKGROUND_SIZE                     (unsigned long)0x2260

#define        IMG_FM_BACKGROUND                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x233a40)
#define        IMG_FM_BACKGROUND_WIDTH                               128
#define        IMG_FM_BACKGROUND_HEIGTH                              160
#define        IMG_FM_BACKGROUND_SIZE                                (unsigned long)0xa000

#define        IMG_FM_BACKGROUND01                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x23da40)
#define        IMG_FM_BACKGROUND01_WIDTH                             72
#define        IMG_FM_BACKGROUND01_HEIGTH                            20
#define        IMG_FM_BACKGROUND01_SIZE                              (unsigned long)0xb40

#define        IMG_FM_SCROLL1                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x23e580)
#define        IMG_FM_SCROLL1_WIDTH                                  4
#define        IMG_FM_SCROLL1_HEIGTH                                 7
#define        IMG_FM_SCROLL1_SIZE                                   (unsigned long)0x38

#define        IMG_FM_SCROLL1NOSEL                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x23e5b8)
#define        IMG_FM_SCROLL1NOSEL_WIDTH                             4
#define        IMG_FM_SCROLL1NOSEL_HEIGTH                            7
#define        IMG_FM_SCROLL1NOSEL_SIZE                              (unsigned long)0x38

#define        IMG_FM_MENU_BACKGROUND                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x23e5f0)
#define        IMG_FM_MENU_BACKGROUND_WIDTH                          66
#define        IMG_FM_MENU_BACKGROUND_HEIGTH                         84
#define        IMG_FM_MENU_BACKGROUND_SIZE                           (unsigned long)0x2b50

#define        IMG_FM_MENU_BACKGROUND1                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x241140)
#define        IMG_FM_MENU_BACKGROUND1_WIDTH                         90
#define        IMG_FM_MENU_BACKGROUND1_HEIGTH                        55
#define        IMG_FM_MENU_BACKGROUND1_SIZE                          (unsigned long)0x26ac

#define        IMG_FM_FREBACKGROUND                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2437ec)
#define        IMG_FM_FREBACKGROUND_WIDTH                            70
#define        IMG_FM_FREBACKGROUND_HEIGTH                           35
#define        IMG_FM_FREBACKGROUND_SIZE                             (unsigned long)0x1324

#define        IMG_FM_SAVEBACKGROUND                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x244b10)
#define        IMG_FM_SAVEBACKGROUND_WIDTH                           90
#define        IMG_FM_SAVEBACKGROUND_HEIGTH                          21
#define        IMG_FM_SAVEBACKGROUND_SIZE                            (unsigned long)0xec4

#define        IMG_FM_SAVEBACKGROUND1                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2459d4)
#define        IMG_FM_SAVEBACKGROUND1_WIDTH                          90
#define        IMG_FM_SAVEBACKGROUND1_HEIGTH                         69
#define        IMG_FM_SAVEBACKGROUND1_SIZE                           (unsigned long)0x3084

#define        IMG_FM_FREGUAGE                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248a58)
#define        IMG_FM_FREGUAGE_WIDTH                                 1
#define        IMG_FM_FREGUAGE_HEIGTH                                5
#define        IMG_FM_FREGUAGE_SIZE                                  (unsigned long)0xa

#define        IMG_FM_FREGUAGE_BK                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248a62)
#define        IMG_FM_FREGUAGE_BK_WIDTH                              1
#define        IMG_FM_FREGUAGE_BK_HEIGTH                             5
#define        IMG_FM_FREGUAGE_BK_SIZE                               (unsigned long)0xa

#define        IMG_FM_VOLUME_GUAGE                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248a6c)
#define        IMG_FM_VOLUME_GUAGE_WIDTH                             1
#define        IMG_FM_VOLUME_GUAGE_HEIGTH                            4
#define        IMG_FM_VOLUME_GUAGE_SIZE                              (unsigned long)0x8

#define        IMG_FM_VOLUME_GUAGE_BK                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248a74)
#define        IMG_FM_VOLUME_GUAGE_BK_WIDTH                          1
#define        IMG_FM_VOLUME_GUAGE_BK_HEIGTH                         4
#define        IMG_FM_VOLUME_GUAGE_BK_SIZE                           (unsigned long)0x8

#define        IMG_FM_VOLUME_BK                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248a7c)
#define        IMG_FM_VOLUME_BK_WIDTH                                12
#define        IMG_FM_VOLUME_BK_HEIGTH                               12
#define        IMG_FM_VOLUME_BK_SIZE                                 (unsigned long)0x120

#define        IMG_FM_SMALLLOCK                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248b9c)
#define        IMG_FM_SMALLLOCK_WIDTH                                12
#define        IMG_FM_SMALLLOCK_HEIGTH                               12
#define        IMG_FM_SMALLLOCK_SIZE                                 (unsigned long)0x120

#define        IMG_FM_SMALLLOCK_BACK                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248cbc)
#define        IMG_FM_SMALLLOCK_BACK_WIDTH                           12
#define        IMG_FM_SMALLLOCK_BACK_HEIGTH                          12
#define        IMG_FM_SMALLLOCK_BACK_SIZE                            (unsigned long)0x120

#define        IMG_FM_CH_BACK                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x248ddc)
#define        IMG_FM_CH_BACK_WIDTH                                  30
#define        IMG_FM_CH_BACK_HEIGTH                                 12
#define        IMG_FM_CH_BACK_SIZE                                   (unsigned long)0x2d0

#define        IMG_FM_STEREO                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2490ac)
#define        IMG_FM_STEREO_WIDTH                                   47
#define        IMG_FM_STEREO_HEIGTH                                  12
#define        IMG_FM_STEREO_SIZE                                    (unsigned long)0x468

#define        IMG_MIC_BACKGROUND                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x249514)
#define        IMG_MIC_BACKGROUND_WIDTH                              128
#define        IMG_MIC_BACKGROUND_HEIGTH                             160
#define        IMG_MIC_BACKGROUND_SIZE                               (unsigned long)0xa000

#define        IMG_RECORD_FODERNAMEBACKGROUND                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x253514)
#define        IMG_RECORD_FODERNAMEBACKGROUND_WIDTH                  105
#define        IMG_RECORD_FODERNAMEBACKGROUND_HEIGTH                 14
#define        IMG_RECORD_FODERNAMEBACKGROUND_SIZE                   (unsigned long)0xb7c

#define        IMG_RECORD_FILENAMEBACKGROUND                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x254090)
#define        IMG_RECORD_FILENAMEBACKGROUND_WIDTH                   105
#define        IMG_RECORD_FILENAMEBACKGROUND_HEIGTH                  12
#define        IMG_RECORD_FILENAMEBACKGROUND_SIZE                    (unsigned long)0x9d8

#define        IMG_RECORD_TOTLETIMEBACKGROUND                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x254a68)
#define        IMG_RECORD_TOTLETIMEBACKGROUND_WIDTH                  48
#define        IMG_RECORD_TOTLETIMEBACKGROUND_HEIGTH                 13
#define        IMG_RECORD_TOTLETIMEBACKGROUND_SIZE                   (unsigned long)0x4e0

#define        IMG_RECORD_QUALITYHIGH                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x254f48)
#define        IMG_RECORD_QUALITYHIGH_WIDTH                          19
#define        IMG_RECORD_QUALITYHIGH_HEIGTH                         16
#define        IMG_RECORD_QUALITYHIGH_SIZE                           (unsigned long)0x260

#define        IMG_RECORD_QUALITYLOW                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2551a8)
#define        IMG_RECORD_QUALITYLOW_WIDTH                           19
#define        IMG_RECORD_QUALITYLOW_HEIGTH                          16
#define        IMG_RECORD_QUALITYLOW_SIZE                            (unsigned long)0x260

#define        IMG_RECORD_SMALLOCK                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x255408)
#define        IMG_RECORD_SMALLOCK_WIDTH                             12
#define        IMG_RECORD_SMALLOCK_HEIGTH                            12
#define        IMG_RECORD_SMALLOCK_SIZE                              (unsigned long)0x120

#define        IMG_RECORD_SMALLOCK_BACK                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x255528)
#define        IMG_RECORD_SMALLOCK_BACK_WIDTH                        12
#define        IMG_RECORD_SMALLOCK_BACK_HEIGTH                       12
#define        IMG_RECORD_SMALLOCK_BACK_SIZE                         (unsigned long)0x120

#define        IMG_RECORD_CURRTIME_BACK                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x255648)
#define        IMG_RECORD_CURRTIME_BACK_WIDTH                        48
#define        IMG_RECORD_CURRTIME_BACK_HEIGTH                       12
#define        IMG_RECORD_CURRTIME_BACK_SIZE                         (unsigned long)0x480

#define        IMG_RECORD_SELBOX0                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x255ac8)
#define        IMG_RECORD_SELBOX0_WIDTH                              70
#define        IMG_RECORD_SELBOX0_HEIGTH                             56
#define        IMG_RECORD_SELBOX0_SIZE                               (unsigned long)0x1ea0

#define        IMG_RECORD_SELBOX1                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x257968)
#define        IMG_RECORD_SELBOX1_WIDTH                              70
#define        IMG_RECORD_SELBOX1_HEIGTH                             56
#define        IMG_RECORD_SELBOX1_SIZE                               (unsigned long)0x1ea0

#define        IMG_TEXT_CONTENTBACKGROUND0                           (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x259808)
#define        IMG_TEXT_CONTENTBACKGROUND0_WIDTH                     110
#define        IMG_TEXT_CONTENTBACKGROUND0_HEIGTH                    95
#define        IMG_TEXT_CONTENTBACKGROUND0_SIZE                      (unsigned long)0x51a4

#define        IMG_TEXT_SCROLLBACKGROUND0                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25e9ac)
#define        IMG_TEXT_SCROLLBACKGROUND0_WIDTH                      8
#define        IMG_TEXT_SCROLLBACKGROUND0_HEIGTH                     97
#define        IMG_TEXT_SCROLLBACKGROUND0_SIZE                       (unsigned long)0x610

#define        IMG_TEXT_SCROLL0                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25efbc)
#define        IMG_TEXT_SCROLL0_WIDTH                                8
#define        IMG_TEXT_SCROLL0_HEIGTH                               15
#define        IMG_TEXT_SCROLL0_SIZE                                 (unsigned long)0xf0

#define        IMG_TEXT_SCROLL1                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25f0ac)
#define        IMG_TEXT_SCROLL1_WIDTH                                8
#define        IMG_TEXT_SCROLL1_HEIGTH                               15
#define        IMG_TEXT_SCROLL1_SIZE                                 (unsigned long)0xf0

#define        IMG_TEXT_SMALLLOCK                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25f19c)
#define        IMG_TEXT_SMALLLOCK_WIDTH                              12
#define        IMG_TEXT_SMALLLOCK_HEIGTH                             12
#define        IMG_TEXT_SMALLLOCK_SIZE                               (unsigned long)0x120

#define        IMG_TEXT_SMALLLOCK_BACK                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25f2bc)
#define        IMG_TEXT_SMALLLOCK_BACK_WIDTH                         12
#define        IMG_TEXT_SMALLLOCK_BACK_HEIGTH                        12
#define        IMG_TEXT_SMALLLOCK_BACK_SIZE                          (unsigned long)0x120

#define        IMG_TEXT_MANE_BACK                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25f3dc)
#define        IMG_TEXT_MANE_BACK_WIDTH                              81
#define        IMG_TEXT_MANE_BACK_HEIGTH                             15
#define        IMG_TEXT_MANE_BACK_SIZE                               (unsigned long)0x97e

#define        IMG_TEXT_MARKBACKGROUND                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x25fd5a)
#define        IMG_TEXT_MARKBACKGROUND_WIDTH                         63
#define        IMG_TEXT_MARKBACKGROUND_HEIGTH                        13
#define        IMG_TEXT_MARKBACKGROUND_SIZE                          (unsigned long)0x666

#define        IMG_TEXT_PAGEBACKGROUND                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2603c0)
#define        IMG_TEXT_PAGEBACKGROUND_WIDTH                         30
#define        IMG_TEXT_PAGEBACKGROUND_HEIGTH                        17
#define        IMG_TEXT_PAGEBACKGROUND_SIZE                          (unsigned long)0x3fc

#define        IMG_TEXT_STATUS_PAUSE                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2607bc)
#define        IMG_TEXT_STATUS_PAUSE_WIDTH                           15
#define        IMG_TEXT_STATUS_PAUSE_HEIGTH                          15
#define        IMG_TEXT_STATUS_PAUSE_SIZE                            (unsigned long)0x1c2

#define        IMG_TEXT_STATUS_PLAY                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26097e)
#define        IMG_TEXT_STATUS_PLAY_WIDTH                            16
#define        IMG_TEXT_STATUS_PLAY_HEIGTH                           15
#define        IMG_TEXT_STATUS_PLAY_SIZE                             (unsigned long)0x1e0

#define        IMG_BOOKMASK_WIN                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x260b5e)
#define        IMG_BOOKMASK_WIN_WIDTH                                92
#define        IMG_BOOKMASK_WIN_HEIGTH                               72
#define        IMG_BOOKMASK_WIN_SIZE                                 (unsigned long)0x33c0

#define        IMG_BROWSER_SMALLLOCK                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x263f1e)
#define        IMG_BROWSER_SMALLLOCK_WIDTH                           12
#define        IMG_BROWSER_SMALLLOCK_HEIGTH                          12
#define        IMG_BROWSER_SMALLLOCK_SIZE                            (unsigned long)0x120

#define        IMG_BROWSER_SMALLLOCK_BACK                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26403e)
#define        IMG_BROWSER_SMALLLOCK_BACK_WIDTH                      12
#define        IMG_BROWSER_SMALLLOCK_BACK_HEIGTH                     12
#define        IMG_BROWSER_SMALLLOCK_BACK_SIZE                       (unsigned long)0x120

#define        IMG_BROWSER_CONTENTBACKGROUND                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26415e)
#define        IMG_BROWSER_CONTENTBACKGROUND_WIDTH                   111
#define        IMG_BROWSER_CONTENTBACKGROUND_HEIGTH                  95
#define        IMG_BROWSER_CONTENTBACKGROUND_SIZE                    (unsigned long)0x5262

#define        IMG_BROWSER_FILETYPE_FOLDER                           (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2693c0)
#define        IMG_BROWSER_FILETYPE_FOLDER_WIDTH                     12
#define        IMG_BROWSER_FILETYPE_FOLDER_HEIGTH                    12
#define        IMG_BROWSER_FILETYPE_FOLDER_SIZE                      (unsigned long)0x120

#define        IMG_BROWSER_FILETYPE_MUSIC                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2694e0)
#define        IMG_BROWSER_FILETYPE_MUSIC_WIDTH                      12
#define        IMG_BROWSER_FILETYPE_MUSIC_HEIGTH                     12
#define        IMG_BROWSER_FILETYPE_MUSIC_SIZE                       (unsigned long)0x120

#define        IMG_BROWSER_FILETYPE_VIDEO                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x269600)
#define        IMG_BROWSER_FILETYPE_VIDEO_WIDTH                      12
#define        IMG_BROWSER_FILETYPE_VIDEO_HEIGTH                     12
#define        IMG_BROWSER_FILETYPE_VIDEO_SIZE                       (unsigned long)0x120

#define        IMG_BROWSER_FILETYPE_TEXT                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x269720)
#define        IMG_BROWSER_FILETYPE_TEXT_WIDTH                       12
#define        IMG_BROWSER_FILETYPE_TEXT_HEIGTH                      12
#define        IMG_BROWSER_FILETYPE_TEXT_SIZE                        (unsigned long)0x120

#define        IMG_BROWSER_FILETYPE_PICTURE                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x269840)
#define        IMG_BROWSER_FILETYPE_PICTURE_WIDTH                    12
#define        IMG_BROWSER_FILETYPE_PICTURE_HEIGTH                   12
#define        IMG_BROWSER_FILETYPE_PICTURE_SIZE                     (unsigned long)0x120

#define        IMG_BROWSER_FILETYPE_OTHER                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x269960)
#define        IMG_BROWSER_FILETYPE_OTHER_WIDTH                      12
#define        IMG_BROWSER_FILETYPE_OTHER_HEIGTH                     12
#define        IMG_BROWSER_FILETYPE_OTHER_SIZE                       (unsigned long)0x120

#define        IMG_BROWSER_SCROLLBACKGROUND                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x269a80)
#define        IMG_BROWSER_SCROLLBACKGROUND_WIDTH                    8
#define        IMG_BROWSER_SCROLLBACKGROUND_HEIGTH                   97
#define        IMG_BROWSER_SCROLLBACKGROUND_SIZE                     (unsigned long)0x610

#define        IMG_BROWSER_SCROLL                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26a090)
#define        IMG_BROWSER_SCROLL_WIDTH                              8
#define        IMG_BROWSER_SCROLL_HEIGTH                             15
#define        IMG_BROWSER_SCROLL_SIZE                               (unsigned long)0xf0

#define        IMG_BROWSER_ITEMBARBACK                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26a180)
#define        IMG_BROWSER_ITEMBARBACK_WIDTH                         95
#define        IMG_BROWSER_ITEMBARBACK_HEIGTH                        15
#define        IMG_BROWSER_ITEMBARBACK_SIZE                          (unsigned long)0xb22

#define        IMG_BROWSER_BATTERY01                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26aca2)
#define        IMG_BROWSER_BATTERY01_WIDTH                           20
#define        IMG_BROWSER_BATTERY01_HEIGTH                          12
#define        IMG_BROWSER_BATTERY01_SIZE                            (unsigned long)0x1e0

#define        IMG_BROWSER_BATTERY02                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26ae82)
#define        IMG_BROWSER_BATTERY02_WIDTH                           20
#define        IMG_BROWSER_BATTERY02_HEIGTH                          12
#define        IMG_BROWSER_BATTERY02_SIZE                            (unsigned long)0x1e0

#define        IMG_BROWSER_BATTERY03                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26b062)
#define        IMG_BROWSER_BATTERY03_WIDTH                           20
#define        IMG_BROWSER_BATTERY03_HEIGTH                          12
#define        IMG_BROWSER_BATTERY03_SIZE                            (unsigned long)0x1e0

#define        IMG_BROWSER_BATTERY04                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26b242)
#define        IMG_BROWSER_BATTERY04_WIDTH                           20
#define        IMG_BROWSER_BATTERY04_HEIGTH                          12
#define        IMG_BROWSER_BATTERY04_SIZE                            (unsigned long)0x1e0

#define        IMG_BROWSER_BATTERY04                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26b422)
#define        IMG_BROWSER_BATTERY04_WIDTH                           20
#define        IMG_BROWSER_BATTERY04_HEIGTH                          12
#define        IMG_BROWSER_BATTERY04_SIZE                            (unsigned long)0x1e0

#define        IMG_BROWSER_BACKGROUND                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x26b602)
#define        IMG_BROWSER_BACKGROUND_WIDTH                          128
#define        IMG_BROWSER_BACKGROUND_HEIGTH                         160
#define        IMG_BROWSER_BACKGROUND_SIZE                           (unsigned long)0xa000

#define        IMG_BROWSER_SCOLL                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x275602)
#define        IMG_BROWSER_SCOLL_WIDTH                               6
#define        IMG_BROWSER_SCOLL_HEIGTH                              144
#define        IMG_BROWSER_SCOLL_SIZE                                (unsigned long)0x6c0

#define        IMG_BROWSER_SCOLL_BLOCK                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x275cc2)
#define        IMG_BROWSER_SCOLL_BLOCK_WIDTH                         5
#define        IMG_BROWSER_SCOLL_BLOCK_HEIGTH                        16
#define        IMG_BROWSER_SCOLL_BLOCK_SIZE                          (unsigned long)0xa0

#define        IMG_SETMENU_BACKGROUND                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x275d62)
#define        IMG_SETMENU_BACKGROUND_WIDTH                          128
#define        IMG_SETMENU_BACKGROUND_HEIGTH                         128
#define        IMG_SETMENU_BACKGROUND_SIZE                           (unsigned long)0x8000

#define        IMG_SETMENU_CONTENTBACKGROUND                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x27dd62)
#define        IMG_SETMENU_CONTENTBACKGROUND_WIDTH                   110
#define        IMG_SETMENU_CONTENTBACKGROUND_HEIGTH                  95
#define        IMG_SETMENU_CONTENTBACKGROUND_SIZE                    (unsigned long)0x51a4

#define        IMG_SETMENU_ICON_NOSEL                                (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x282f06)
#define        IMG_SETMENU_ICON_NOSEL_WIDTH                          12
#define        IMG_SETMENU_ICON_NOSEL_HEIGTH                         12
#define        IMG_SETMENU_ICON_NOSEL_SIZE                           (unsigned long)0x120

#define        IMG_SETMENU_ICON_SEL                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x283026)
#define        IMG_SETMENU_ICON_SEL_WIDTH                            12
#define        IMG_SETMENU_ICON_SEL_HEIGTH                           12
#define        IMG_SETMENU_ICON_SEL_SIZE                             (unsigned long)0x120

#define        IMG_SETMENU_SCROLLBACKGROUND                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x283146)
#define        IMG_SETMENU_SCROLLBACKGROUND_WIDTH                    8
#define        IMG_SETMENU_SCROLLBACKGROUND_HEIGTH                   97
#define        IMG_SETMENU_SCROLLBACKGROUND_SIZE                     (unsigned long)0x610

#define        IMG_SETMENU_SCROLL1                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x283756)
#define        IMG_SETMENU_SCROLL1_WIDTH                             8
#define        IMG_SETMENU_SCROLL1_HEIGTH                            15
#define        IMG_SETMENU_SCROLL1_SIZE                              (unsigned long)0xf0

#define        IMG_SETMENU_VERBACKGROUND                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x283846)
#define        IMG_SETMENU_VERBACKGROUND_WIDTH                       100
#define        IMG_SETMENU_VERBACKGROUND_HEIGTH                      80
#define        IMG_SETMENU_VERBACKGROUND_SIZE                        (unsigned long)0x3e80

#define        IMG_FILEFOLDER_ICON                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2876c6)
#define        IMG_FILEFOLDER_ICON_WIDTH                             16
#define        IMG_FILEFOLDER_ICON_HEIGTH                            16
#define        IMG_FILEFOLDER_ICON_SIZE                              (unsigned long)0x200

#define        IMG_ICON_SEL                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2878c6)
#define        IMG_ICON_SEL_WIDTH                                    12
#define        IMG_ICON_SEL_HEIGTH                                   12
#define        IMG_ICON_SEL_SIZE                                     (unsigned long)0x120

#define        IMG_JEPG_ICON                                         (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2879e6)
#define        IMG_JEPG_ICON_WIDTH                                   16
#define        IMG_JEPG_ICON_HEIGTH                                  16
#define        IMG_JEPG_ICON_SIZE                                    (unsigned long)0x200

#define        IMG_LOUDSPEAKER_OFF1                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x287be6)
#define        IMG_LOUDSPEAKER_OFF1_WIDTH                            12
#define        IMG_LOUDSPEAKER_OFF1_HEIGTH                           12
#define        IMG_LOUDSPEAKER_OFF1_SIZE                             (unsigned long)0x120

#define        IMG_LOUDSPEAKER_OFF                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x287d06)
#define        IMG_LOUDSPEAKER_OFF_WIDTH                             12
#define        IMG_LOUDSPEAKER_OFF_HEIGTH                            12
#define        IMG_LOUDSPEAKER_OFF_SIZE                              (unsigned long)0x120

#define        IMG_LOUDSPEAKER_ON1                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x287e26)
#define        IMG_LOUDSPEAKER_ON1_WIDTH                             12
#define        IMG_LOUDSPEAKER_ON1_HEIGTH                            12
#define        IMG_LOUDSPEAKER_ON1_SIZE                              (unsigned long)0x120

#define        IMG_LOUDSPEAKER_ON                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x287f46)
#define        IMG_LOUDSPEAKER_ON_WIDTH                              12
#define        IMG_LOUDSPEAKER_ON_HEIGTH                             12
#define        IMG_LOUDSPEAKER_ON_SIZE                               (unsigned long)0x120

#define        IMG_MUSIC_ICON                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x288066)
#define        IMG_MUSIC_ICON_WIDTH                                  16
#define        IMG_MUSIC_ICON_HEIGTH                                 16
#define        IMG_MUSIC_ICON_SIZE                                   (unsigned long)0x200

#define        IMG_PLAY_SCROLL                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x288266)
#define        IMG_PLAY_SCROLL_WIDTH                                 1
#define        IMG_PLAY_SCROLL_HEIGTH                                7
#define        IMG_PLAY_SCROLL_SIZE                                  (unsigned long)0xe

#define        IMG_PLAY_SCROLLBLANK                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x288274)
#define        IMG_PLAY_SCROLLBLANK_WIDTH                            1
#define        IMG_PLAY_SCROLLBLANK_HEIGTH                           7
#define        IMG_PLAY_SCROLLBLANK_SIZE                             (unsigned long)0xe

#define        IMG_PONIT_NOSEL                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x288282)
#define        IMG_PONIT_NOSEL_WIDTH                                 12
#define        IMG_PONIT_NOSEL_HEIGTH                                12
#define        IMG_PONIT_NOSEL_SIZE                                  (unsigned long)0x120

#define        IMG_SEL_ICON                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2883a2)
#define        IMG_SEL_ICON_WIDTH                                    100
#define        IMG_SEL_ICON_HEIGTH                                   16
#define        IMG_SEL_ICON_SIZE                                     (unsigned long)0xc80

#define        IMG_SETMENU_BACKGROUND1                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x289022)
#define        IMG_SETMENU_BACKGROUND1_WIDTH                         160
#define        IMG_SETMENU_BACKGROUND1_HEIGTH                        128
#define        IMG_SETMENU_BACKGROUND1_SIZE                          (unsigned long)0xa000

#define        IMG_SETMENU_USERSEL01                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x293022)
#define        IMG_SETMENU_USERSEL01_WIDTH                           13
#define        IMG_SETMENU_USERSEL01_HEIGTH                          69
#define        IMG_SETMENU_USERSEL01_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERSEL02                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x293724)
#define        IMG_SETMENU_USERSEL02_WIDTH                           13
#define        IMG_SETMENU_USERSEL02_HEIGTH                          69
#define        IMG_SETMENU_USERSEL02_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERSEL03                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x293e26)
#define        IMG_SETMENU_USERSEL03_WIDTH                           13
#define        IMG_SETMENU_USERSEL03_HEIGTH                          69
#define        IMG_SETMENU_USERSEL03_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERSEL04                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x294528)
#define        IMG_SETMENU_USERSEL04_WIDTH                           13
#define        IMG_SETMENU_USERSEL04_HEIGTH                          69
#define        IMG_SETMENU_USERSEL04_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERSEL05                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x294c2a)
#define        IMG_SETMENU_USERSEL05_WIDTH                           13
#define        IMG_SETMENU_USERSEL05_HEIGTH                          69
#define        IMG_SETMENU_USERSEL05_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERSEL06                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x29532c)
#define        IMG_SETMENU_USERSEL06_WIDTH                           13
#define        IMG_SETMENU_USERSEL06_HEIGTH                          69
#define        IMG_SETMENU_USERSEL06_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERSEL07                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x295a2e)
#define        IMG_SETMENU_USERSEL07_WIDTH                           13
#define        IMG_SETMENU_USERSEL07_HEIGTH                          69
#define        IMG_SETMENU_USERSEL07_SIZE                            (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL01                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x296130)
#define        IMG_SETMENU_USERNOSEL01_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL01_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL01_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL02                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x296832)
#define        IMG_SETMENU_USERNOSEL02_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL02_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL02_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL03                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x296f34)
#define        IMG_SETMENU_USERNOSEL03_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL03_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL03_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL04                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x297636)
#define        IMG_SETMENU_USERNOSEL04_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL04_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL04_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL05                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x297d38)
#define        IMG_SETMENU_USERNOSEL05_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL05_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL05_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL06                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x29843a)
#define        IMG_SETMENU_USERNOSEL06_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL06_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL06_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USERNOSEL07                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x298b3c)
#define        IMG_SETMENU_USERNOSEL07_WIDTH                         13
#define        IMG_SETMENU_USERNOSEL07_HEIGTH                        69
#define        IMG_SETMENU_USERNOSEL07_SIZE                          (unsigned long)0x702

#define        IMG_SETMENU_USEREQSETTING                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x29923e)
#define        IMG_SETMENU_USEREQSETTING_WIDTH                       128
#define        IMG_SETMENU_USEREQSETTING_HEIGTH                      160
#define        IMG_SETMENU_USEREQSETTING_SIZE                        (unsigned long)0xa000

#define        IMG_SPECTRUM_BACKGROUND                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2a323e)
#define        IMG_SPECTRUM_BACKGROUND_WIDTH                         63
#define        IMG_SPECTRUM_BACKGROUND_HEIGTH                        13
#define        IMG_SPECTRUM_BACKGROUND_SIZE                          (unsigned long)0x666

#define        IMG_USB_BACKGROUND0                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2a38a4)
#define        IMG_USB_BACKGROUND0_WIDTH                             160
#define        IMG_USB_BACKGROUND0_HEIGTH                            128
#define        IMG_USB_BACKGROUND0_SIZE                              (unsigned long)0xa000

#define        IMG_WARNING_BOX                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2ad8a4)
#define        IMG_WARNING_BOX_WIDTH                                 120
#define        IMG_WARNING_BOX_HEIGTH                                87
#define        IMG_WARNING_BOX_SIZE                                  (unsigned long)0x5190

#define        IMG_SYSTEM_LOCKON                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2b2a34)
#define        IMG_SYSTEM_LOCKON_WIDTH                               128
#define        IMG_SYSTEM_LOCKON_HEIGTH                              160
#define        IMG_SYSTEM_LOCKON_SIZE                                (unsigned long)0xa000

#define        IMG_SYSTEM_LOCKOFF                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2bca34)
#define        IMG_SYSTEM_LOCKOFF_WIDTH                              128
#define        IMG_SYSTEM_LOCKOFF_HEIGTH                             160
#define        IMG_SYSTEM_LOCKOFF_SIZE                               (unsigned long)0xa000

#define        IMG_UNSPORTTEDPIC                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2c6a34)
#define        IMG_UNSPORTTEDPIC_WIDTH                               112
#define        IMG_UNSPORTTEDPIC_HEIGTH                              64
#define        IMG_UNSPORTTEDPIC_SIZE                                (unsigned long)0x3800

#define        IMG_SEL01_ICON                                        (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2ca234)
#define        IMG_SEL01_ICON_WIDTH                                  37
#define        IMG_SEL01_ICON_HEIGTH                                 16
#define        IMG_SEL01_ICON_SIZE                                   (unsigned long)0x4a0

#define        IMG_NOSEL00_ICON                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2ca6d4)
#define        IMG_NOSEL00_ICON_WIDTH                                37
#define        IMG_NOSEL00_ICON_HEIGTH                               16
#define        IMG_NOSEL00_ICON_SIZE                                 (unsigned long)0x4a0

#define        IMG_MEDIABRO_BACKGROUND                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2cab74)
#define        IMG_MEDIABRO_BACKGROUND_WIDTH                         86
#define        IMG_MEDIABRO_BACKGROUND_HEIGTH                        70
#define        IMG_MEDIABRO_BACKGROUND_SIZE                          (unsigned long)0x2f08

#define        IMG_MEDIABRO_NOSEL_BACK                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2cda7c)
#define        IMG_MEDIABRO_NOSEL_BACK_WIDTH                         86
#define        IMG_MEDIABRO_NOSEL_BACK_HEIGTH                        16
#define        IMG_MEDIABRO_NOSEL_BACK_SIZE                          (unsigned long)0xac0

#define        IMG_MEDIABRO_SEL_BACK                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2ce53c)
#define        IMG_MEDIABRO_SEL_BACK_WIDTH                           86
#define        IMG_MEDIABRO_SEL_BACK_HEIGTH                          16
#define        IMG_MEDIABRO_SEL_BACK_SIZE                            (unsigned long)0xac0

#define        IMG_MEIDASORTBAK0                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2ceffc)
#define        IMG_MEIDASORTBAK0_WIDTH                               90
#define        IMG_MEIDASORTBAK0_HEIGTH                              16
#define        IMG_MEIDASORTBAK0_SIZE                                (unsigned long)0xb40

#define        IMG_MEIDASORTBAK1                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2cfb3c)
#define        IMG_MEIDASORTBAK1_WIDTH                               90
#define        IMG_MEIDASORTBAK1_HEIGTH                              16
#define        IMG_MEIDASORTBAK1_SIZE                                (unsigned long)0xb40

#define        IMG_MEIDASORTBAK2                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2d067c)
#define        IMG_MEIDASORTBAK2_WIDTH                               90
#define        IMG_MEIDASORTBAK2_HEIGTH                              16
#define        IMG_MEIDASORTBAK2_SIZE                                (unsigned long)0xb40

#define        IMG_MEIDASORTBAK3                                     (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2d11bc)
#define        IMG_MEIDASORTBAK3_WIDTH                               90
#define        IMG_MEIDASORTBAK3_HEIGTH                              16
#define        IMG_MEIDASORTBAK3_SIZE                                (unsigned long)0xb40

#define        IMG_MDB_BACKGROUND                                    (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2d1cfc)
#define        IMG_MDB_BACKGROUND_WIDTH                              128
#define        IMG_MDB_BACKGROUND_HEIGTH                             160
#define        IMG_MDB_BACKGROUND_SIZE                               (unsigned long)0xa000

#define        IMG_NOWPLAY                                           (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dbcfc)
#define        IMG_NOWPLAY_WIDTH                                     12
#define        IMG_NOWPLAY_HEIGTH                                    12
#define        IMG_NOWPLAY_SIZE                                      (unsigned long)0x120

#define        IMG_ALLMUSIC                                          (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dbe1c)
#define        IMG_ALLMUSIC_WIDTH                                    12
#define        IMG_ALLMUSIC_HEIGTH                                   12
#define        IMG_ALLMUSIC_SIZE                                     (unsigned long)0x120

#define        IMG_SINGER                                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dbf3c)
#define        IMG_SINGER_WIDTH                                      12
#define        IMG_SINGER_HEIGTH                                     12
#define        IMG_SINGER_SIZE                                       (unsigned long)0x120

#define        IMG_ABLUM                                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc05c)
#define        IMG_ABLUM_WIDTH                                       12
#define        IMG_ABLUM_HEIGTH                                      12
#define        IMG_ABLUM_SIZE                                        (unsigned long)0x120

#define        IMG_GENRE                                             (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc17c)
#define        IMG_GENRE_WIDTH                                       12
#define        IMG_GENRE_HEIGTH                                      12
#define        IMG_GENRE_SIZE                                        (unsigned long)0x120

#define        IMG_LIST                                              (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc29c)
#define        IMG_LIST_WIDTH                                        12
#define        IMG_LIST_HEIGTH                                       12
#define        IMG_LIST_SIZE                                         (unsigned long)0x120

#define        IMG_MEDIA_RECORDFILE                                  (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc3bc)
#define        IMG_MEDIA_RECORDFILE_WIDTH                            12
#define        IMG_MEDIA_RECORDFILE_HEIGTH                           12
#define        IMG_MEDIA_RECORDFILE_SIZE                             (unsigned long)0x120

#define        IMG_MYFAVO                                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc4dc)
#define        IMG_MYFAVO_WIDTH                                      12
#define        IMG_MYFAVO_HEIGTH                                     12
#define        IMG_MYFAVO_SIZE                                       (unsigned long)0x120

#define        IMG_MEDIAUPDATA                                       (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc5fc)
#define        IMG_MEDIAUPDATA_WIDTH                                 12
#define        IMG_MEDIAUPDATA_HEIGTH                                12
#define        IMG_MEDIAUPDATA_SIZE                                  (unsigned long)0x120

#define        IMG_BREAKPOINT_PLAY                                   (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc71c)
#define        IMG_BREAKPOINT_PLAY_WIDTH                             12
#define        IMG_BREAKPOINT_PLAY_HEIGTH                            12
#define        IMG_BREAKPOINT_PLAY_SIZE                              (unsigned long)0x120

#define        IMG_MEDIA_CONTENTBACKGROUND                           (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2dc83c)
#define        IMG_MEDIA_CONTENTBACKGROUND_WIDTH                     110
#define        IMG_MEDIA_CONTENTBACKGROUND_HEIGTH                    95
#define        IMG_MEDIA_CONTENTBACKGROUND_SIZE                      (unsigned long)0x51a4

#define        IMG_MEDIA_ITEMBARBACK                                 (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2e19e0)
#define        IMG_MEDIA_ITEMBARBACK_WIDTH                           95
#define        IMG_MEDIA_ITEMBARBACK_HEIGTH                          15
#define        IMG_MEDIA_ITEMBARBACK_SIZE                            (unsigned long)0xb22

#define        IMG_MEDIA_ITEMBARNOSEL0                               (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2e2502)
#define        IMG_MEDIA_ITEMBARNOSEL0_WIDTH                         96
#define        IMG_MEDIA_ITEMBARNOSEL0_HEIGTH                        16
#define        IMG_MEDIA_ITEMBARNOSEL0_SIZE                          (unsigned long)0xc00

#define        IMG_MEDIA_SCROLL                                      (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2e3102)
#define        IMG_MEDIA_SCROLL_WIDTH                                8
#define        IMG_MEDIA_SCROLL_HEIGTH                               15
#define        IMG_MEDIA_SCROLL_SIZE                                 (unsigned long)0xf0

#define        IMG_MEDIA_SCROLLBACKGROUND                            (IMAGE_IN_FLASH_BASE_ADDR + (unsigned long)0x2e31f2)
#define        IMG_MEDIA_SCROLLBACKGROUND_WIDTH                      8
#define        IMG_MEDIA_SCROLLBACKGROUND_HEIGTH                     97
#define        IMG_MEDIA_SCROLLBACKGROUND_SIZE                       (unsigned long)0x610


#endif
